sudo: required
services:
  - docker

before_install:
  - docker build -t phuongminh2303/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phuongminh2303/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-aws-travis"
  env: "DockerAwsTravis-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-732409576677"
  bucket_path: "docker-aws-travis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY