sudo: required
services: 
  - docker

before_install:
  - docker build -t phuongminh2303/docker-aws-travis -f Dockerfile.dev .

script:
 - docker run -e CI=true phuongminh2303/docker-aws-travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "ap-southeast-1"
  app: "docker-aws-travis"
  env: "DockerAwsTravis-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-732409576677"
  bucket_path: "docker-aws-travis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"